sudo: required
dist: trusty
addons:
  artifacts:
    paths:
      - results
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - '7'
cache:
  directories:
    - node_modules
    - bower_components
    - $HOME/.npm
    - $HOME/.cache
before_script:
  - npm install
before_deploy:
  - npm run build
env:
  global:
    - NODE_ENV=testing
    - ARTIFACTS_BUCKET=js-tasks-ru
    - secure: >-
        lkglOfrqqyPAII34kGA5yLXDPUS0XjPa8cu9QOXdwFMwYDUlbC17Gt7YUcrIjpN6jfsmLKS8nydfahGIIpmViAY2aAPEBQIN2Dgp03ouCOL1tqutnRP5hCWfY2yMJMgF1UVLHmti/O+jhWWWTJDumW73W1s+CyrrN/X9E5pFwOlvNrXLdQMlqV+OhSR0bPoU1Wl2074yAIUkDLvEX78jQh6reGLwCMTQa0L450OT29UydcR0ASXa7kxFnrgHPBwnaquVZhSphnOkOxBhU5KallnNzAJUUhOkRnpIxiJE4KN5JpgmUkTfTvG8pihyxjo/bdX1YKvpbTgAr1yT8xNRWdF4mrpPFJR1aFG8sZQd72XU5TSIED2nmAVjEfYzttK0meXkEeByOwQ3bu1v1s7iDb1SLGjvmiIYG7s33qM2omN2KU0bXtxdP559Zq3tsBl7S+CYstH58l+mlw0detV+tt1n71q8Refjh+TbJrOxCuLZ3kY1iuwvJxEFhftlH8cCPBCP+xQJWJGKfXTtZq3w6Ucpz+k6xNb8N43ptmAPDqHAc6z3VLi0eCqgYSr+yALao1QALMn1JTXcNNTu3EDRxZ4MY1o3sH7uEnO1olbgcKcdnwf+u0o6KtqTRH65j/Y8P53RcILKdwwiZvGtfyaNoBmfDUOP45ODXBH7WQ0BccA=
    - secure: >-
        d2293FYZO6ouo/igUeC07Ow57yXZjOvT0+dfWFIA3JugO9c/f0125ssSqPupsdne6Xyst4eqZlCEYEI0d/HA++VI9/gosFYV1lFvBUTopgY2olPFGafrPOBoBCRjj140Q9zZ76s77FnbHCcMKqpwjs0gCxAaDzK6pqwdjbbSxryYh1JmCXUJEWTZqKeRGJnMsML7i7r/yr/eNqB6R8OJvjirWOETehkVNTlFG3kL1n/W1nm0S9bAFB/uqa3SwC1mhMyrn2T3iGkjdwO+xiNb0RADej5lxCL9l8GwYaExELfraUvw8qVvqkvqauDklU2OcIsE1BO6xLIdqg0+G/G4PcdGlVwhNjG6UyrccuTPb6MoXbKw6E2S7np34TiyDceb9pkNYiv2zd7w4u6u7vBnloALi1DO+voXKVN1FjLGM54O3tLPeM6ysAWYLYin2IkTZubSpgzWoucIh/ANYc3N739yEqw8xhHxgZ9tCw2Ap0Rj9z5p03AoojGhkwWIStVF/v07KfqFifPsBWs8yWL6yu8Ml+yB+oI1auVKqfV39PXeFpaRmAYyOmz6mT6GfgeUBS+zTMhNUBcIttQE+SCtbQpSdY+er3nTAv50meBJnPE58DWeWmjVfjwH/9KPCyiU8pVoa80lZwD2wskSg842Vuvogf8L4jBslapY7U+5W7k=
script:
  - npm run test
notifications:
  webhooks: 'http://learn.javascript.ru/automation/ci/build'
