sudo: required
dist: trusty
addons:
  artifacts:
    paths:
      - results
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - '7'
cache:
  directories:
    - node_modules
    - bower_components
    - $HOME/.npm
    - $HOME/.cache
before_script:
  - npm install
before_deploy:
  - npm run build
env:
  global:
    - NODE_ENV=testing
    - ARTIFACTS_BUCKET=js-tasks-ru
    - secure: >-
        F2wEfNPnaMc0zBhwgcephMA/VlbN/xE4x3qkBJHqD4rLwaJSoD2vHCzdim/3aYA6GkaPdeI5NvwOr2WrcezazbPNVTrcbvBrSGK/lQ0WH+hEoTiyxomJ96vd866RkgfKK2ToI1AWnkoILivBeju8G+7SQFquVxv3PJhHM3c/Td8CxroSrJP/VRgeKW5fVtzg9dGxyq2JiIIQ/feJhcO6vG3BVH9jdZyl13rMpcj5zj9S591lHFMk016XMTwUymN0qdtM8uduYjjZBIJaN+CP1GevX3EHj+g5PkpeeWtdMhGteeVHxXKPzrBuwjprYSx1by/zg+vqYAu5gOsFtuycOPO9DLzTWCdex9At4XGN+1/Sv/p0mNyREzDTL45L/GrQiEs/Ix33Bdn8drW2exGHlCNtSw17FsENF+nHeQAffB26NPBt686BXrKlddtwymCyu+3I3Id+1FB4sns1LPc0zy6MSOV9jBd1RkT5bxFQyseWArCheSAyUVhT+AAIOnGq7VEp49GISD0YNt+X4Vo64p304pKhBrBk6heIcC2WWHu//VqudQ/1b93Ue9Hr0GZlQ/GDYhiaFf0b+y8snF3p3CCULidg+fIhDCpFsWQUYNDoNwsFeypKFAtHH+CSIgc3N7NVIeGBHw6iG7LTA2d6+00Z+RFoIsRhrAPu7VkhTmI=
    - secure: >-
        ikUtTet1k6nZoDI0rfJAoNhPF51pwjq4k0W9x39+EnKZ0WQpVxE8+40up89/P1eMeN9D1ZjcDVr1V3x0SSKeBVkUzmuXTJTb968B9S7VKGgptk74gDZt8Dya0hughC55MmV5a2kZ5wrdoqB0NMWDYJRxmI+lZfDgzKW/stYLeOHmff9BGV8alTMiTX9NGnF8lHH9FVnm0j6sG1i9cmUosmGin+v67Q1XjWhD6gLzCbYwGxLkH2MACUkx7H18Knkw1VK797BhNLXOCMC+xAAu/ZGWb32mcnSaqJtVT8WDiY3daWtN+VcEeH63SWcJd+SkVkvfmGwgxvHsZU9yfSeyIv1ig0AMUmlscBt4M4yFoOPFrLtOhALPIhnC3zGt6PK+RuLLJ7TIpWzMQiBGvoUq9G+vhZ50O3zFRoxQsF0wVa/8Y72NggmLFPiklGlrzsrY2uQi1Sbo76CnzaD315/FPOMvbfl4sAWK9bGXuuaT8a+HVaTIjIYW+bChaEO/obcRueJcqguHSvpI/C+SDFw8U0L44OIqjTVqh/w/ep8y1zCkeTqD0YaKUSz9eXMvtbKIUMXokd7Fd83wa5KYxMY2Mv4iDBjFUznVu3iBSSqcVH6LfLmUoYHD3PRQ0wgAkeAq5A2DSGeqVGxIdQEjO3Hl4dmOvTQeg5Kc7PuO2CsWH5M=
script:
  - npm run test
notifications:
  webhooks: 'http://learn.javascript.ru/automation/ci/build'
