sudo: required
dist: trusty
addons:
  artifacts:
    paths:
      - results
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - '7'
cache:
  directories:
    - node_modules
    - bower_components
    - $HOME/.npm
    - $HOME/.cache
before_script:
  - npm install
before_deploy:
  - npm run build
env:
  global:
    - NODE_ENV=testing
    - ARTIFACTS_BUCKET=js-tasks-ru
    - secure: >-
        nTj88hdnEBBWV0ZBpL9X7JqR5fQgSUY5TY34FTW2IZq2BtXEt3d8GeepV0tBz1XW5qQZ4gu+GRuxFPFeHpQSheiteJSrPqIdHGjQTOFs/vKKKxL3p/8sFi6w71oY0fGizX1LgrpHNYxl3LrrcshgMgTwHIOZGQRGZQ5/rlRwKo0vi4aVH3//9XLEEp9ZQHP/eRUb5OmMgXGj/2RkdllVkrGkuqSGH3r4HTWH7/aicSD6BSw/AAQa2YVRWIS3jcwp/B9QOdWwh9ylojwfFUwLfTYuzVZCZ2aPF4ih4ft4NCj+/asKBQ8Jxw0p0tFJqT7pZ65gh10CkQuHdI0iRV5JeHEcUXttmfVS3khrSbTEE0dzrT2910L52zLqY4F0ltOohhwmkgeLB1O87e2/5qqrt7AnHZVLQjjA+gj6tkDZgvVesMcclqFQFJmuUJXzvhZ7hlJqo/VAbkGzEDZNVyk8mWTBU09TwXR/lo7J01ozuxHCbnXRt+LmzDuqpNW8TxRWotifI0PbEOTIOlOQ6tIVVgyh1dZXM+l70bJmJuNl7QYvkmnTk79mWmVEEe0rlx4R9oSD04/dWTRLFNjQdkRKwApYQqzyQHcHH0dZtTU3F1JlrM3wz1XtPIYC17r4fasqXLH3S8NIqtZZ5Oc4F4vvxsAOs5N5E+GDB+XYtoFowDE=
    - secure: >-
        NAAEnrx6qhvOucnfZzj1hLobCCCGM2qux1iv6HZRwKOjqlSUtvfObcYtiiNTnvYNNtprDyC9jh3NguJRoNVDQviAPlAko4TSCR2GJACqt6+J0w7mkX+/TqcAHrHxxYTexTV1kNc5/Z1o1V2UDy+l7galZe4tAPyUJkpg6sqLp5uyKQW3siUDEzzWuKNf4JAGwb25RR72PYM0+/nMfIbOiw+QP+CgaPau+ZDPO8TxlCCB8GqBxUOBCNs3CUD59VBEPoca8dvTJbQNTElh8vXlUDITci9YguGiu96tv47ZdGxiKe2QQbj7n8FUeHYMhYhTWlo6BF4gzUKUdm28UlkxUi0Rb+b3YpD7shYB0DXJQNIRLDER2F9Ww3lzNFBJMboZww8HL7+EUD2utSIOq7nPZKBNHdLLADQnC3knX28Rx7xQtRbDTXL7J/BgyUTBWdBCWtUmPMrJKTJQ9I5ANOyqXTiB5LKvJUxtwLu+h78VpDd6ylLFXU8W/LTg22P6csqN62yap1ke2Vf6IU02rMllUf0NUzWQIH6NWXcRM/Ma0bOy1QvCKfRb27Ee7HqTnVGxMyq1tlh5LBG9BppIjOWoPjhJ9k1NrTxndGuZ4+yWEPWr67hkqr1h5c2M3vw0HDnwuHgb7Syh7H9ekjfpBttpIuAi2JAWcBMuJQQf2I7NdyQ=
script:
  - npm run test
notifications:
  webhooks: 'http://learn.javascript.ru/automation/ci/build'
